# Site settings
title: IT干货网
email: it@mkmd.cn
description: "IT互联网干货汇总"
baseurl: ""
url: "http://mkmd.cn"
twitter_username: liulantao
github_username:  Lax

# Build settings
markdown: kramdown
permalink: pretty

exclude: [Rakefile, _crawler, _raw]
permalink: /posts/:year/:year-:month-:day-:title.html

comment_uyan_uid: 1936498
releated_posts_limit: 3
google_analytics_tracking_id: UA-1658815-7
google_analytics_tracking_name: mkmd.cn
