# Site settings
title: IT技术干货
subtitle: 科技与互联网信息
email: iftti@iftti.com
description: "[IT技术干货iftti.com] @KernelHacks"
baseurl: ""
url: "http://iftti.com"
twitter_username: liulantao
github_username:  Lax
googleplus_username: LiuLantao
author:
  name: Liu Lantao

# Build settings
markdown: kramdown
permalink: pretty

exclude: [Rakefile, _crawler, _raw, Gemfile, Gemfile.lock]
permalink: /posts/:year/:year-:month-:day-:title.html

maillist_qq_nid: 6be92ef3590ee662cd5e6381ab2044c328716364f684cf3e
comment_uyan_uid: 1936498
releated_posts_limit: 3
google_analytics_tracking_id: UA-1658815-7
google_analytics_tracking_name: iftti.com
